# _config.yml is for configuring Jekyll as the SSG.  See https://jekyllrb.com/docs/configuration/ and https://jekyllrb.com/docs/configuration/default/

# Jekyll automatically ignores trying to build HTML out of folders starting w/ an underscore, unless you opt them back in over here.

title: 'Tiny GitHub Pages Site built with Jekyll'
description: 'A teeny-tiny Jekyll site hosted on GitHub Pages'
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .ignoreme/

defaults:
  - scope:
      path: pages
      type: pages
    values:
      permalink: /:title
      layout: ordinary_page